"""create initial tables

Revision ID: 88359928dee0
Revises: 
Create Date: 2026-09-18 10:05:38.394646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88359928dee0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('unit_label', sa.String(length=30), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activity_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+([_-][a-z0-9]+)*$'", name='ck_activity_type_slug_format'),
    sa.CheckConstraint(
        "(is_system = TRUE AND user_id IS NULL) "
        "OR (is_system = FALSE AND user_id IS NOT NULL)",
        name="ck_activity_type_system",
    ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_activity_type_slug', 'activity_types', ['slug'], unique=True, postgresql_where=sa.text('is_system = TRUE'))
    op.create_index('uq_activity_type_user_slug', 'activity_types', ['user_id', 'slug'], unique=True, postgresql_where=sa.text('is_system = FALSE'))
    op.create_table('activity_type_unit_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_type_id', sa.Uuid(), nullable=False),
    sa.Column('unit_type_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('per_set', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_type_id', 'unit_type_id', name='uq_activity_type_unit_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_type_unit_types')
    op.drop_index('uq_activity_type_user_slug', table_name='activity_types', postgresql_where=sa.text('is_system = FALSE'))
    op.drop_index('uq_activity_type_slug', table_name='activity_types', postgresql_where=sa.text('is_system = TRUE'))
    op.drop_table('activity_types')
    op.drop_table('users')
    op.drop_table('unit_types')
    # ### end Alembic commands ###
